---
config:
  flowchart:
    defaultRenderer: "elk"
---
%% graph with custom configuration cannot be rendered in Markdown PDF
flowchart LR
  A((A))
  B((B))
  C((C))
  D((D))
  E((E))
  F((F))
  G((G))

  A <--> B
  A <--> D

  B --> D
  B --> E

  C --> B
  C --> D

  E --> C
  E --> G

  F --> E
  F --> D
  F <--> G
